# Go cross compiler (xgo): Go 1.12.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM vegaprotocol/xgo-1.12.17:latest

MAINTAINER Péter Szilágyi <peterke@gmail.com>
