# Go cross compiler (xgo): Go 1.14.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

#FROM karalabe/xgo-1.14.3
FROM docker.pkg.github.com/vegaprotocol/xgo/xgo-1.14.3:latest

MAINTAINER Péter Szilágyi <peterke@gmail.com>
