# Go cross compiler (xgo): Go 1.11.x
# Copyright (c) 2018 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

#FROM karalabe/xgo-1.11.13
FROM docker.pkg.github.com/vegaprotocol/xgo/xgo-1.11.13:latest

MAINTAINER Péter Szilágyi <peterke@gmail.com>
